// Code generated by github.com/caerbannogwhite/enchanter/generators. DO NOT EDIT.

package series

import (
	"fmt"

	"github.com/caerbannogwhite/enchanter"
)

func (s NAs) Not() Series {
	return s
}

func (s NAs) And(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot AND %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot AND %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot AND %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Or(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot OR %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = o.Data_[0]
			return Bools{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = o.Data_[i]
			}
			return Bools{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = o.Data_[0]
			}
			return Bools{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = o.Data_[i]
			}
			return Bools{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot OR %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot OR %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Mul(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Div(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Mod(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Exp(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Add(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(enchanter.NA_TEXT + *o.Data_[0])
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(enchanter.NA_TEXT + *o.Data_[i])
			}
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(enchanter.NA_TEXT + *o.Data_[0])
			}
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(enchanter.NA_TEXT + *o.Data_[i])
			}
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Sub(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Eq(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Ne(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Gt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Ge(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Lt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s NAs) Le(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}
