// Code generated by github.com/caerbannogwhite/enchanter/generators. DO NOT EDIT.

package series

import "fmt"

func (s Strings) And(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot AND %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Or(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot OR %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Mul(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Div(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Mod(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Exp(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Add(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + boolToString(o.data[0]))
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + boolToString(o.data[i]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + boolToString(o.data[0]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + boolToString(o.data[i]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + intToString(int64(o.data[0])))
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + intToString(int64(o.data[i])))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + intToString(int64(o.data[0])))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + intToString(int64(o.data[i])))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + intToString(o.data[0]))
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + intToString(o.data[i]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + intToString(o.data[0]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + intToString(o.data[i]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + floatToString(o.data[0]))
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + floatToString(o.data[i]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + floatToString(o.data[0]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + floatToString(o.data[i]))
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + *o.data[0])
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + *o.data[i])
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + *o.data[0])
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + *o.data[i])
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + o.data[0].String())
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + o.data[i].String())
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + o.data[0].String())
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + o.data[i].String())
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = s.ctx.StringPool.Put(*s.data[0] + o.data[0].String())
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[0] + o.data[i].String())
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + o.data[0].String())
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.ctx.StringPool.Put(*s.data[i] + o.data[i].String())
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Sub(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Eq(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = *s.data[0] == *o.data[0]
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[0] == *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] == *o.data[0]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] == *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Ne(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = *s.data[0] != *o.data[0]
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[0] != *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] != *o.data[0]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] != *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Gt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = *s.data[0] > *o.data[0]
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[0] > *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] > *o.data[0]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] > *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Ge(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = *s.data[0] >= *o.data[0]
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[0] >= *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] >= *o.data[0]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] >= *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Lt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = *s.data[0] < *o.data[0]
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[0] < *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] < *o.data[0]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] < *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Le(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			result[0] = *s.data[0] <= *o.data[0]
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[0] <= *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] <= *o.data[0]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.data[i] <= *o.data[i]
			}
			return Bools{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

	// Coalesce fills the null elements of the series with the corresponding
	// elements of other: the result takes this series' value where it is not
	// null and the other operand's value where it is. A result element is null
	// only when both operands are null there. The body is produced by the code
	// generator, like every other operator in this file.

}

func (s Strings) Coalesce(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.ctx)
	}
	if s.ctx != otherSeries.Context() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.ctx, otherSeries.Context())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, true, resultSize)
			if s.isNullable && s.nullMask[0]&1 != 0 {
				result[0] = o.data[0]
			} else {
				result[0] = s.data[0]
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.isNullable, s.nullMask, true, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.isNullable && s.nullMask[0]&1 != 0 {
					result[i] = o.data[i]
				} else {
					result[i] = s.data[0]
				}
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.isNullable && s.nullMask[i>>3]&(1<<uint(i%8)) != 0 {
					result[i] = o.data[0]
				} else {
					result[i] = s.data[i]
				}
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.isNullable, s.nullMask, false, o.isNullable, o.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.isNullable && s.nullMask[i>>3]&(1<<uint(i%8)) != 0 {
					result[i] = o.data[i]
				} else {
					result[i] = s.data[i]
				}
			}
			return Strings{isNullable: resultIsNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.isNullable, s.nullMask, true, resultSize)
			result[0] = s.data[0]
			return Strings{isNullable: s.isNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.isNullable, s.nullMask, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.data[0]
			}
			return Strings{isNullable: s.isNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.isNullable, s.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.data[i]
			}
			return Strings{isNullable: s.isNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.isNullable, s.nullMask, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.data[i]
			}
			return Strings{isNullable: s.isNullable, nullMask: resultNullMask, data: result, ctx: s.ctx}
		}
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	}

}

// Not is the logical negation of a boolean series. Only Bools and NAs
// support it, so on this type it returns an error series.
func (s Strings) Not() Series {
	return Errors{fmt.Sprintf("Cannot NOT %s", s.Type().String())}
}
