// Code generated by github.com/caerbannogwhite/enchanter/generators. DO NOT EDIT.

package series

import (
	"fmt"

	"github.com/caerbannogwhite/enchanter"
)

func (s Strings) And(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot AND %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Or(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot OR %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Mul(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Div(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Mod(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Exp(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Add(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Bools:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + boolToString(o.Data_[0]))
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + boolToString(o.Data_[i]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + boolToString(o.Data_[0]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + boolToString(o.Data_[i]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Ints:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + intToString(int64(o.Data_[0])))
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + intToString(int64(o.Data_[i])))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + intToString(int64(o.Data_[0])))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + intToString(int64(o.Data_[i])))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Int64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + intToString(o.Data_[0]))
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + intToString(o.Data_[i]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + intToString(o.Data_[0]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + intToString(o.Data_[i]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Float64s:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + floatToString(o.Data_[0]))
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + floatToString(o.Data_[i]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + floatToString(o.Data_[0]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + floatToString(o.Data_[i]))
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + *o.Data_[0])
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + *o.Data_[i])
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + *o.Data_[0])
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + *o.Data_[i])
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + o.Data_[0].String())
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + o.Data_[i].String())
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + o.Data_[0].String())
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + o.Data_[i].String())
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + o.Data_[0].String())
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + o.Data_[i].String())
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + o.Data_[0].String())
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + o.Data_[i].String())
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, true, resultSize)
			result[0] = s.Ctx_.StringPool.Put(*s.Data_[0] + enchanter.NA_TEXT)
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[0] + enchanter.NA_TEXT)
			}
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + enchanter.NA_TEXT)
			}
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Ctx_.StringPool.Put(*s.Data_[i] + enchanter.NA_TEXT)
			}
			return Strings{IsNullable_: false, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Sub(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Eq(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = *s.Data_[0] == *o.Data_[0]
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[0] == *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] == *o.Data_[0]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] == *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Ne(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = *s.Data_[0] != *o.Data_[0]
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[0] != *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] != *o.Data_[0]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] != *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Gt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = *s.Data_[0] > *o.Data_[0]
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[0] > *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] > *o.Data_[0]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] > *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Ge(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = *s.Data_[0] >= *o.Data_[0]
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[0] >= *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] >= *o.Data_[0]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] >= *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Lt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = *s.Data_[0] < *o.Data_[0]
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[0] < *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] < *o.Data_[0]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] < *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Strings) Le(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = *s.Data_[0] <= *o.Data_[0]
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[0] <= *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] <= *o.Data_[0]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = *s.Data_[i] <= *o.Data_[i]
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}

// Coalesce fills the null elements of the series with the corresponding
// elements of other: the result takes this series' value where it is not
// null and the other operand's value where it is. A result element is null
// only when both operands are null there. The body is produced by the code
// generator, like every other operator in this file.
func (s Strings) Coalesce(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			if s.IsNullable_ && s.NullMask_[0]&1 != 0 {
				result[0] = o.Data_[0]
			} else {
				result[0] = s.Data_[0]
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.IsNullable_ && s.NullMask_[0]&1 != 0 {
					result[i] = o.Data_[i]
				} else {
					result[i] = s.Data_[0]
				}
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.IsNullable_ && s.NullMask_[i>>3]&(1<<uint(i%8)) != 0 {
					result[i] = o.Data_[0]
				} else {
					result[i] = s.Data_[i]
				}
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.IsNullable_ && s.NullMask_[i>>3]&(1<<uint(i%8)) != 0 {
					result[i] = o.Data_[i]
				} else {
					result[i] = s.Data_[i]
				}
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, true, resultSize)
			result[0] = s.Data_[0]
			return Strings{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0]
			}
			return Strings{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i]
			}
			return Strings{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i]
			}
			return Strings{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	}

}
