// Code generated by github.com/caerbannogwhite/enchanter/generators. DO NOT EDIT.

package series

import (
	"fmt"
	"time"
)

func (s Times) And(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot AND %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Or(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot OR %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Mul(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot multiply %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Div(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot divide %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Mod(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot use modulo %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Exp(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	default:
		return Errors{fmt.Sprintf("Cannot use exponentiation %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Add(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Strings:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = o.Ctx_.StringPool.Put(s.Data_[0].String() + *o.Data_[0])
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = o.Ctx_.StringPool.Put(s.Data_[0].String() + *o.Data_[i])
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = o.Ctx_.StringPool.Put(s.Data_[i].String() + *o.Data_[0])
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]*string, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = o.Ctx_.StringPool.Put(s.Data_[i].String() + *o.Data_[i])
			}
			return Strings{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].AddDate(o.Data_[0].Year(), int(o.Data_[0].Month()), o.Data_[0].Day())
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].AddDate(o.Data_[i].Year(), int(o.Data_[i].Month()), o.Data_[i].Day())
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].AddDate(o.Data_[0].Year(), int(o.Data_[0].Month()), o.Data_[0].Day())
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].AddDate(o.Data_[i].Year(), int(o.Data_[i].Month()), o.Data_[i].Day())
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Add(o.Data_[0])
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Add(o.Data_[i])
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Add(o.Data_[0])
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Add(o.Data_[i])
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot sum %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Sub(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Duration, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Sub(o.Data_[0])
			return Durations{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Duration, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Sub(o.Data_[i])
			}
			return Durations{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]time.Duration, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Sub(o.Data_[0])
			}
			return Durations{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]time.Duration, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Sub(o.Data_[i])
			}
			return Durations{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	case Durations:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Add(-o.Data_[0])
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Add(-o.Data_[i])
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Add(-o.Data_[0])
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Add(-o.Data_[i])
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot subtract %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Eq(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Compare(o.Data_[0]) == 0
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Compare(o.Data_[i]) == 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[0]) == 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[i]) == 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for equality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Ne(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Compare(o.Data_[0]) != 0
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Compare(o.Data_[i]) != 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[0]) != 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[i]) != 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case s.Len() == 1:
			resultSize := o.Len()
			return NAs{size: resultSize}
		case o.Len() == 1:
			resultSize := s.Len()
			return NAs{size: resultSize}
		case s.Len() == o.Len():
			resultSize := s.Len()
			return NAs{size: resultSize}
		}
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for inequality %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Gt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Compare(o.Data_[0]) == 1
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Compare(o.Data_[i]) == 1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[0]) == 1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[i]) == 1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Ge(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Compare(o.Data_[0]) >= 1
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Compare(o.Data_[i]) >= 1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[0]) >= 1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[i]) >= 1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for greater than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Lt(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Compare(o.Data_[0]) == -1
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Compare(o.Data_[i]) == -1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[0]) == -1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[i]) == -1
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than %s and %s", s.Type().String(), o.Type().String())}
	}

}

func (s Times) Le(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			result[0] = s.Data_[0].Compare(o.Data_[0]) <= 0
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0].Compare(o.Data_[i]) <= 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[0]) <= 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]bool, resultSize)
			resultNullMask, resultIsNullable := binaryNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i].Compare(o.Data_[i]) <= 0
			}
			return Bools{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot compare for less than or equal to %s and %s", s.Type().String(), o.Type().String())}
	}

}

// Coalesce fills the null elements of the series with the corresponding
// elements of other: the result takes this series' value where it is not
// null and the other operand's value where it is. A result element is null
// only when both operands are null there. The body is produced by the code
// generator, like every other operator in this file.
func (s Times) Coalesce(other any) Series {
	var otherSeries Series
	if _, ok := other.(Series); ok {
		otherSeries = other.(Series)
	} else {
		otherSeries = NewSeries(other, nil, false, false, s.Ctx_)
	}
	if s.Ctx_ != otherSeries.GetContext() {
		return Errors{fmt.Sprintf("Cannot operate on series with different contexts: %v and %v", s.Ctx_, otherSeries.GetContext())}
	}
	switch o := otherSeries.(type) {
	case Times:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, true, resultSize)
			if s.IsNullable_ && s.NullMask_[0]&1 != 0 {
				result[0] = o.Data_[0]
			} else {
				result[0] = s.Data_[0]
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, true, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.IsNullable_ && s.NullMask_[0]&1 != 0 {
					result[i] = o.Data_[i]
				} else {
					result[i] = s.Data_[0]
				}
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.IsNullable_ && s.NullMask_[i>>3]&(1<<uint(i%8)) != 0 {
					result[i] = o.Data_[0]
				} else {
					result[i] = s.Data_[i]
				}
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask, resultIsNullable := coalesceNullMask(s.IsNullable_, s.NullMask_, false, o.IsNullable_, o.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				if s.IsNullable_ && s.NullMask_[i>>3]&(1<<uint(i%8)) != 0 {
					result[i] = o.Data_[i]
				} else {
					result[i] = s.Data_[i]
				}
			}
			return Times{IsNullable_: resultIsNullable, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	case NAs:
		switch {
		case s.Len() == 1 && o.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, true, resultSize)
			result[0] = s.Data_[0]
			return Times{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == 1:
			resultSize := o.Len()
			result := make([]time.Time, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, true, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[0]
			}
			return Times{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case o.Len() == 1:
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i]
			}
			return Times{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		case s.Len() == o.Len():
			resultSize := s.Len()
			result := make([]time.Time, resultSize)
			resultNullMask := naOperandNullMask(s.IsNullable_, s.NullMask_, false, resultSize)
			for i := 0; i < resultSize; i++ {
				result[i] = s.Data_[i]
			}
			return Times{IsNullable_: s.IsNullable_, NullMask_: resultNullMask, Data_: result, Ctx_: s.Ctx_}
		}
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	default:
		return Errors{fmt.Sprintf("Cannot coalesce %s and %s", s.Type().String(), o.Type().String())}
	}

}
